apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-system-admin-deployment
  labels:
    tier: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: admin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        tier: admin
    spec:
      containers:
        - name: ecommerce-system-admin-deployment-container
          image: ngophuocloi/test-turbo-admin:v2
          ports:
            - containerPort: 3002
          envFrom:
          - secretRef:
              name:  ecommerce-system-frontend-secret
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-system-admin-service
spec:
  ports:
    - port: 80
      targetPort: 3002
  selector:
    tier: admin
