apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-system-onlineshop-deployment
  labels:
    tier: onlineshop
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: onlineshop
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        tier: onlineshop
    spec:
      containers:
        - name: ecommerce-system-onlineshop-deployment-container
          image: ngophuocloi/test-turbo-online-shop:v1
          ports:
            - containerPort: 3001
          envFrom:
          - secretRef:
              name:  ecommerce-system-frontend-secret
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-system-onlineshop-service
spec:
  ports:
    - port: 80
      targetPort: 3001
  selector:
    tier: onlineshop
